- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - infra

- hosts: master
  remote_user: centos
  become: true
  vars_files:
    - vars.yml
  roles:
    - role: machines
      vars:
        hostname: k8sm1
    - kubernetes_ini
    - nginx

- hosts: minions
  remote_user: centos
  become: true
  roles:
    - role: machines
      vars:
        hostname: k8sn{{groups['minions'].index(inventory_hostname)|int + 1}}
    - kubernetes_join

- hosts: master
  remote_user: centos
  become: true
  tasks:
    - name: Output the address
      command: kubectl get pods --selector=app=nginx -o jsonpath='{.items[*].status.hostIP}'
