- hosts: localhost
  tasks:
  - name: Create a new keypair
    ec2_key:
      name: k8s-keypair
      region: eu-west-1
    register: ec2_key

  - name: save private key
    copy:
      content: "{{ ec2_key.key.private_key }}"
      dest: "~/.ssh/k8s-keypair.pem"
      mode: 0600
    when: ec2_key.changed
