- name: Change hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Add host to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ansible_default_ipv4.address}}"
    line: "{{ ansible_default_ipv4.address }} {{ hostname }}"
    state: present
