- name: Launch kubeadm in master
  shell: "kubeadm config images pull"

- name: Launch kubeadm in master
  shell: "kubeadm init --apiserver-advertise-address {{ ansible_eth0.ipv4.address }}"

- name: Get join command in master
  shell: "kubeadm token create --print-join-command"
  register: output_kubeadm

- set_fact:
    kubeadm_cmd: "{{output_kubeadm.stdout}}"

- debug: msg="Output {{kubeadm_cmd}}"
